/**
 * Pure token transforms: W3C Design Tokens JSON in, CSS / TypeScript / Sketch
 * palette text out. No dependencies, no I/O — build-tokens.mjs does the I/O
 * and tokens.test.ts exercises these directly.
 *
 * Supported `$type`s: color, dimension, number, duration, cubicBezier,
 * fontFamily, fontWeight, shadow, string. Groups may declare `$type` for their
 * children. Any string value may embed `{path.to.token}` aliases.
 */

export const CSS_PREFIX = 'lp'

// MARK: - Flatten

/**
 * Walks the token tree and returns a flat list of `{ path, type, value, description, dark }`
 * in source order. `path` is an array of segments.
 */
export function flatten(tree, inheritedType = null, path = [], out = []) {
  for (const [key, node] of Object.entries(tree)) {
    if (key.startsWith('$')) continue
    if (node === null || typeof node !== 'object') continue
    const type = node.$type ?? inheritedType
    if ('$value' in node) {
      out.push({
        path: [...path, key],
        type,
        value: node.$value,
        description: node.$description,
        dark: node.$extensions?.['com.rao.lp']?.dark,
      })
    } else {
      flatten(node, type, [...path, key], out)
    }
  }
  return out
}

// MARK: - Aliases

const ALIAS = /\{([^}]+)\}/g

/** Resolves `{a.b.c}` references (whole-value or embedded) with cycle detection. */
export function resolveAliases(tokens) {
  const byName = new Map(tokens.map((t) => [t.path.join('.'), t]))
  const resolved = new Map()

  function resolveValue(value, stack) {
    if (typeof value === 'string') {
      return value.replace(ALIAS, (_, ref) => {
        const target = byName.get(ref.trim())
        if (!target) throw new Error(`Unknown token alias {${ref}} in ${stack.at(-1) ?? 'value'}`)
        const v = resolveToken(target, stack)
        return typeof v === 'string' || typeof v === 'number' ? String(v) : JSON.stringify(v)
      })
    }
    if (Array.isArray(value)) return value.map((v) => resolveValue(v, stack))
    if (value && typeof value === 'object') {
      return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, resolveValue(v, stack)]))
    }
    return value
  }

  function resolveToken(token, stack = []) {
    const name = token.path.join('.')
    if (resolved.has(name)) return resolved.get(name)
    if (stack.includes(name)) throw new Error(`Alias cycle: ${[...stack, name].join(' -> ')}`)
    const value = resolveValue(token.value, [...stack, name])
    resolved.set(name, value)
    return value
  }

  return tokens.map((t) => ({
    ...t,
    value: resolveToken(t),
    dark: t.dark === undefined ? undefined : resolveValue(t.dark, [t.path.join('.')]),
  }))
}

// MARK: - Formatting

export function cssName(path) {
  return `--${CSS_PREFIX}-${path.join('-')}`
}

function shadowToCss(layers) {
  return layers
    .map((l) => {
      const parts = [l.inset ? 'inset' : null, l.offsetX, l.offsetY, l.blur, l.spread, l.color]
      return parts.filter((p) => p !== null && p !== undefined && p !== '').join(' ')
    })
    .join(', ')
}

/** Serializes one resolved token value as a CSS value. */
export function toCssValue(token, value = token.value) {
  switch (token.type) {
    case 'fontFamily':
      return (Array.isArray(value) ? value : [value])
        .map((f) => (/[\s"']/.test(f) && !f.startsWith('"') ? `"${f}"` : f))
        .join(', ')
    case 'shadow':
      return shadowToCss(Array.isArray(value) ? value : [value])
    default:
      return String(value)
  }
}

export function toCss(tokens) {
  const light = []
  const dark = []
  for (const t of tokens) {
    light.push(`  ${cssName(t.path)}: ${toCssValue(t)};`)
    if (t.dark !== undefined) dark.push(`  ${cssName(t.path)}: ${toCssValue(t, t.dark)};`)
  }
  const header = `/* GENERATED by scripts/build-tokens.mjs from tokens/tokens.json — edit the JSON, not this file. */\n`
  let css = `${header}\n:root {\n${light.join('\n')}\n}\n`
  if (dark.length) css += `\n:root[data-theme='dark'] {\n${dark.join('\n')}\n}\n`
  return css
}

// MARK: - TypeScript

function camel(segment) {
  return segment.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())
}

function tsKey(segment) {
  const k = camel(segment)
  return /^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k)
}

function tsValue(token) {
  if (token.type === 'shadow') return JSON.stringify(toCssValue(token))
  return JSON.stringify(token.value)
}

export function toTs(tokens) {
  const root = {}
  for (const t of tokens) {
    let node = root
    t.path.slice(0, -1).forEach((seg) => {
      node[seg] ??= {}
      node = node[seg]
    })
    node[t.path.at(-1)] = { __leaf: tsValue(t) }
  }

  function render(node, indent) {
    const pad = '  '.repeat(indent)
    const lines = Object.entries(node).map(([k, v]) => {
      const body = '__leaf' in v ? v.__leaf : render(v, indent + 1)
      return `${pad}  ${tsKey(k)}: ${body},`
    })
    return `{\n${lines.join('\n')}\n${pad}}`
  }

  const names = tokens.map((t) => JSON.stringify(t.path.join('-')))
  return [
    `/* GENERATED by scripts/build-tokens.mjs from tokens/tokens.json — edit the JSON, not this file. */`,
    ``,
    `export const tokens = ${render(root, 0)} as const`,
    ``,
    `export const tokenNames = [`,
    ...names.map((n) => `  ${n},`),
    `] as const`,
    ``,
    `export type TokenName = (typeof tokenNames)[number]`,
    ``,
    `/** \`var(--${CSS_PREFIX}-<name>)\` for a token, e.g. cssVar('platinum-2'). */`,
    `export function cssVar(name: TokenName): string {`,
    `  return \`var(--${CSS_PREFIX}-\${name})\``,
    `}`,
    ``,
  ].join('\n')
}

// MARK: - Sketch palette

/** Parses #rgb, #rrggbb, #rrggbbaa, rgb() and rgba() into 0..1 channels. */
export function parseColor(input) {
  const s = String(input).trim()
  const hex = s.match(/^#([0-9a-f]{3,8})$/i)
  if (hex) {
    let h = hex[1]
    if (h.length === 3 || h.length === 4) h = [...h].map((c) => c + c).join('')
    const n = parseInt(h.padEnd(8, 'f'), 16)
    return {
      red: ((n >>> 24) & 255) / 255,
      green: ((n >>> 16) & 255) / 255,
      blue: ((n >>> 8) & 255) / 255,
      alpha: (n & 255) / 255,
    }
  }
  const rgb = s.match(/^rgba?\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*(?:,\s*([\d.]+)\s*)?\)$/i)
  if (rgb) {
    return {
      red: Number(rgb[1]) / 255,
      green: Number(rgb[2]) / 255,
      blue: Number(rgb[3]) / 255,
      alpha: rgb[4] === undefined ? 1 : Number(rgb[4]),
    }
  }
  return null
}

/** Sketch Palettes plugin format. Colors carry no names, so the index file records the order. */
export function toSketchPalette(tokens) {
  const colors = []
  const index = []
  for (const t of tokens) {
    if (t.type !== 'color') continue
    const c = parseColor(t.value)
    if (!c) continue
    colors.push(round(c))
    index.push(t.path.join('.'))
  }
  return {
    palette: JSON.stringify(
      { compatibleVersion: '2.0', pluginVersion: '2.22', colors, gradients: [], images: [] },
      null,
      2,
    ),
    index: index.join('\n') + '\n',
  }
}

function round(c) {
  const r = (x) => Math.round(x * 10000) / 10000
  return { red: r(c.red), green: r(c.green), blue: r(c.blue), alpha: r(c.alpha) }
}

// MARK: - Pipeline

/** Everything in one call: tree in, `{ css, ts, palette, index, tokens }` out. */
export function buildAll(tree) {
  const tokens = resolveAliases(flatten(tree))
  const sketch = toSketchPalette(tokens)
  return { tokens, css: toCss(tokens), ts: toTs(tokens), palette: sketch.palette, index: sketch.index }
}
