/**
 * Pure token transforms: W3C Design Tokens JSON in, CSS / TypeScript / Sketch
 * palette / C header text out. No dependencies, no I/O — build-tokens.mjs does
 * the I/O and tokens.test.ts exercises these directly.
 *
 * Supported `$type`s: color, dimension, number, duration, cubicBezier,
 * fontFamily, fontWeight, shadow, string. Groups may declare `$type` for their
 * children. Any string value may embed `{path.to.token}` aliases.
 */

export const CSS_PREFIX = 'lp'

// MARK: - Flatten

/**
 * Walks the token tree and returns a flat list of `{ path, type, value, description, dark }`
 * in source order. `path` is an array of segments.
 */
export function flatten(tree, inheritedType = null, path = [], out = []) {
  for (const [key, node] of Object.entries(tree)) {
    if (key.startsWith('$')) continue
    if (node === null || typeof node !== 'object') continue
    const type = node.$type ?? inheritedType
    if ('$value' in node) {
      out.push({
        path: [...path, key],
        type,
        value: node.$value,
        description: node.$description,
        dark: node.$extensions?.['com.rao.lp']?.dark,
      })
    } else {
      flatten(node, type, [...path, key], out)
    }
  }
  return out
}

// MARK: - Aliases

const ALIAS = /\{([^}]+)\}/g

/** Resolves `{a.b.c}` references (whole-value or embedded) with cycle detection. */
export function resolveAliases(tokens) {
  const byName = new Map(tokens.map((t) => [t.path.join('.'), t]))
  const resolved = new Map()

  function resolveValue(value, stack) {
    if (typeof value === 'string') {
      return value.replace(ALIAS, (_, ref) => {
        const target = byName.get(ref.trim())
        if (!target) throw new Error(`Unknown token alias {${ref}} in ${stack.at(-1) ?? 'value'}`)
        const v = resolveToken(target, stack)
        return typeof v === 'string' || typeof v === 'number' ? String(v) : JSON.stringify(v)
      })
    }
    if (Array.isArray(value)) return value.map((v) => resolveValue(v, stack))
    if (value && typeof value === 'object') {
      return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, resolveValue(v, stack)]))
    }
    return value
  }

  function resolveToken(token, stack = []) {
    const name = token.path.join('.')
    if (resolved.has(name)) return resolved.get(name)
    if (stack.includes(name)) throw new Error(`Alias cycle: ${[...stack, name].join(' -> ')}`)
    const value = resolveValue(token.value, [...stack, name])
    resolved.set(name, value)
    return value
  }

  return tokens.map((t) => ({
    ...t,
    value: resolveToken(t),
    dark: t.dark === undefined ? undefined : resolveValue(t.dark, [t.path.join('.')]),
  }))
}

// MARK: - Formatting

export function cssName(path) {
  return `--${CSS_PREFIX}-${path.join('-')}`
}

function shadowToCss(layers) {
  return layers
    .map((l) => {
      const parts = [l.inset ? 'inset' : null, l.offsetX, l.offsetY, l.blur, l.spread, l.color]
      return parts.filter((p) => p !== null && p !== undefined && p !== '').join(' ')
    })
    .join(', ')
}

/** Serializes one resolved token value as a CSS value. */
export function toCssValue(token, value = token.value) {
  switch (token.type) {
    case 'fontFamily':
      return (Array.isArray(value) ? value : [value])
        .map((f) => (/[\s"']/.test(f) && !f.startsWith('"') ? `"${f}"` : f))
        .join(', ')
    case 'shadow':
      return shadowToCss(Array.isArray(value) ? value : [value])
    default:
      return String(value)
  }
}

export function toCss(tokens) {
  const light = []
  const dark = []
  for (const t of tokens) {
    light.push(`  ${cssName(t.path)}: ${toCssValue(t)};`)
    if (t.dark !== undefined) dark.push(`  ${cssName(t.path)}: ${toCssValue(t, t.dark)};`)
  }
  const header = `/* GENERATED by scripts/build-tokens.mjs from tokens/tokens.json — edit the JSON, not this file. */\n`
  let css = `${header}\n:root {\n${light.join('\n')}\n}\n`
  if (dark.length) css += `\n:root[data-theme='dark'] {\n${dark.join('\n')}\n}\n`
  return css
}

// MARK: - TypeScript

function camel(segment) {
  return segment.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())
}

function tsKey(segment) {
  const k = camel(segment)
  return /^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k)
}

function tsValue(token) {
  if (token.type === 'shadow') return JSON.stringify(toCssValue(token))
  return JSON.stringify(token.value)
}

export function toTs(tokens) {
  const root = {}
  for (const t of tokens) {
    let node = root
    t.path.slice(0, -1).forEach((seg) => {
      node[seg] ??= {}
      node = node[seg]
    })
    node[t.path.at(-1)] = { __leaf: tsValue(t) }
  }

  function render(node, indent) {
    const pad = '  '.repeat(indent)
    const lines = Object.entries(node).map(([k, v]) => {
      const body = '__leaf' in v ? v.__leaf : render(v, indent + 1)
      return `${pad}  ${tsKey(k)}: ${body},`
    })
    return `{\n${lines.join('\n')}\n${pad}}`
  }

  const names = tokens.map((t) => JSON.stringify(t.path.join('-')))
  return [
    `/* GENERATED by scripts/build-tokens.mjs from tokens/tokens.json — edit the JSON, not this file. */`,
    ``,
    `export const tokens = ${render(root, 0)} as const`,
    ``,
    `export const tokenNames = [`,
    ...names.map((n) => `  ${n},`),
    `] as const`,
    ``,
    `export type TokenName = (typeof tokenNames)[number]`,
    ``,
    `/** \`var(--${CSS_PREFIX}-<name>)\` for a token, e.g. cssVar('platinum-2'). */`,
    `export function cssVar(name: TokenName): string {`,
    `  return \`var(--${CSS_PREFIX}-\${name})\``,
    `}`,
    ``,
  ].join('\n')
}

// MARK: - Sketch palette

/** Parses #rgb, #rrggbb, #rrggbbaa, rgb() and rgba() into 0..1 channels. */
export function parseColor(input) {
  const s = String(input).trim()
  const hex = s.match(/^#([0-9a-f]{3,8})$/i)
  if (hex) {
    let h = hex[1]
    if (h.length === 3 || h.length === 4) h = [...h].map((c) => c + c).join('')
    const n = parseInt(h.padEnd(8, 'f'), 16)
    return {
      red: ((n >>> 24) & 255) / 255,
      green: ((n >>> 16) & 255) / 255,
      blue: ((n >>> 8) & 255) / 255,
      alpha: (n & 255) / 255,
    }
  }
  const rgb = s.match(/^rgba?\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*(?:,\s*([\d.]+)\s*)?\)$/i)
  if (rgb) {
    return {
      red: Number(rgb[1]) / 255,
      green: Number(rgb[2]) / 255,
      blue: Number(rgb[3]) / 255,
      alpha: rgb[4] === undefined ? 1 : Number(rgb[4]),
    }
  }
  return null
}

/** Sketch Palettes plugin format. Colors carry no names, so the index file records the order. */
export function toSketchPalette(tokens) {
  const colors = []
  const index = []
  for (const t of tokens) {
    if (t.type !== 'color') continue
    const c = parseColor(t.value)
    if (!c) continue
    colors.push(round(c))
    index.push(t.path.join('.'))
  }
  return {
    palette: JSON.stringify(
      { compatibleVersion: '2.0', pluginVersion: '2.22', colors, gradients: [], images: [] },
      null,
      2,
    ),
    index: index.join('\n') + '\n',
  }
}

function round(c) {
  const r = (x) => Math.round(x * 10000) / 10000
  return { red: r(c.red), green: r(c.green), blue: r(c.blue), alpha: r(c.alpha) }
}

// MARK: - C (MaryUI/linux)

export const C_PREFIX = 'LP'

/** `accent.blue.focus-ring` → `LP_ACCENT_BLUE_FOCUS_RING`. */
export function cName(path) {
  return `${C_PREFIX}_${path.join('_').replace(/[^A-Za-z0-9]+/g, '_').toUpperCase()}`
}

/** A C float literal that keeps every digit JavaScript prints (0.00005 stays 0.00005f). */
export function cFloat(n) {
  let s = String(Number(n))
  if (!/[.e]/.test(s)) s += '.0'
  return `${s}f`
}

function cColor(value) {
  const c = parseColor(value)
  if (!c) return null
  const r = (x) => cFloat(Math.round(x * 10000) / 10000)
  return `((lp_color){ ${r(c.red)}, ${r(c.green)}, ${r(c.blue)}, ${r(c.alpha)} })`
}

/** `"12px"` → `{ unit: 'px', number: 12 }`, `"105deg"` → `{ unit: 'deg', number: 105 }`, `"0"` → px 0. */
export function cDimension(value) {
  const m = String(value).trim().match(/^(-?[\d.]+)(px|deg|rem|em|%)?$/)
  if (!m) return null
  return { unit: m[2] ?? 'px', number: Number(m[1]) }
}

/** `"120ms"` → 120, `"7s"` → 7000. */
export function cDurationMs(value) {
  const m = String(value).trim().match(/^(-?[\d.]+)(ms|s)$/)
  if (!m) return null
  return Number(m[1]) * (m[2] === 's' ? 1000 : 1)
}

function cBezier(value) {
  const m = String(value).match(/cubic-bezier\(([^)]*)\)/)
  if (!m) return null
  const [a, b, c, d] = m[1].split(',').map(Number)
  return `((lp_cubic_bezier){ ${cFloat(a)}, ${cFloat(b)}, ${cFloat(c)}, ${cFloat(d)} })`
}

function cString(value) {
  return JSON.stringify(String(value))
}

function cShadowLayer(layer) {
  const px = (v) => cFloat(cDimension(v)?.number ?? 0)
  return `{ ${layer.inset ? 1 : 0}, ${px(layer.offsetX)}, ${px(layer.offsetY)}, ${px(layer.blur)}, ${px(layer.spread)}, ${cColor(layer.color)} }`
}

/**
 * The tokens as a C header (include/maryui/lp_tokens.h): colors as lp_color
 * initializers, px dimensions as floats, degrees with a _DEG suffix, durations
 * in ms with a _MS suffix, numbers as ints when integral, font stacks as
 * NULL-terminated _FAMILIES string arrays plus a comma-joined _PANGO string, shadows as
 * lp_shadow_layer arrays with a _COUNT, cubic béziers and springs as structs,
 * and an LP_TOKENS[] table of every token by name for the Gallery and tests.
 */
export function toC(tokens, { sourceHash = 'unknown', tree = null } = {}) {
  const lines = []
  const push = (line = '') => lines.push(line)
  push(`/* GENERATED by web/scripts/build-tokens.mjs from web/tokens/tokens.json (sha256 ${sourceHash}) — edit the JSON, then \`npm run tokens\`. */`)
  push('#ifndef MARYUI_LP_TOKENS_H')
  push('#define MARYUI_LP_TOKENS_H')
  push()
  push('#include <stddef.h>')
  push('#include "maryui/lp_types.h"')
  push()
  push(`#define LP_TOKENS_SOURCE_SHA "${sourceHash}"`)

  let group = null
  const springs = new Map()
  for (const t of tokens) {
    const g = t.path[0]
    if (g !== group) {
      group = g
      const description = tree?.[g]?.$description
      push()
      push(`/* ${g}${description ? `: ${description}` : ''} */`)
    }
    const name = cName(t.path)
    const note = t.description ? `  /* ${t.description} */` : ''
    switch (t.type) {
      case 'color': {
        const c = cColor(t.value)
        push(c ? `#define ${name} ${c}  /* ${t.value} */` : `/* ${name}: unparsable color ${t.value} */`)
        if (t.dark !== undefined && cColor(t.dark)) push(`#define ${name}_DARK ${cColor(t.dark)}  /* ${t.dark} */`)
        break
      }
      case 'dimension': {
        const d = cDimension(t.value)
        if (!d) push(`/* ${name}: ${t.value} */`)
        else if (d.unit === 'deg') push(`#define ${name}_DEG ${cFloat(d.number)}${note}`)
        else push(`#define ${name} ${cFloat(d.number)}  /* ${t.value} */${note}`)
        break
      }
      case 'number':
        push(`#define ${name} ${Number.isInteger(t.value) ? t.value : cFloat(t.value)}${note}`)
        break
      case 'duration': {
        const ms = cDurationMs(t.value)
        push(ms === null ? `/* ${name}: ${t.value} */` : `#define ${name}_MS ${cFloat(ms)}  /* ${t.value} */`)
        break
      }
      case 'cubicBezier': {
        const b = cBezier(t.value)
        push(b ? `#define ${name} ${b}  /* ${t.value} */` : `/* ${name}: ${t.value} */`)
        break
      }
      case 'fontWeight':
        push(`#define ${name} ${t.value}`)
        break
      case 'fontFamily': {
        const list = Array.isArray(t.value) ? t.value : [t.value]
        push(`static const char *const ${name}_FAMILIES[] = { ${list.map(cString).join(', ')}, NULL };`)
        push(`#define ${name}_PANGO ${cString(list.join(', '))}`)
        break
      }
      case 'shadow': {
        const layers = Array.isArray(t.value) ? t.value : [t.value]
        push(`static const lp_shadow_layer ${name}[] = {`)
        for (const layer of layers) push(`    ${cShadowLayer(layer)},`)
        push('};')
        push(`#define ${name}_COUNT ${layers.length}`)
        break
      }
      default:
        push(`#define ${name}_STR ${cString(typeof t.value === 'string' ? t.value : JSON.stringify(t.value))}`)
    }
    const leaf = t.path.at(-1)
    if ((leaf === 'frequency' || leaf === 'damping') && t.type === 'number') {
      const key = t.path.slice(0, -1)
      const entry = springs.get(key.join('.')) ?? { path: key }
      entry[leaf] = t.value
      springs.set(key.join('.'), entry)
    }
  }

  push()
  push('/* Springs: { frequency Hz, damping ratio }, one per group with those two leaves. */')
  for (const spring of springs.values()) {
    if (spring.frequency === undefined || spring.damping === undefined) continue
    push(`#define ${cName(spring.path)} ((lp_spring_params){ ${cFloat(spring.frequency)}, ${cFloat(spring.damping)} })`)
  }

  push()
  push("/* Every token by name, in source order, for the Gallery's Tokens tab and for tests. */")
  push('typedef struct lp_token_info { const char *name; const char *css_name; const char *type; const char *value; } lp_token_info;')
  push('static const lp_token_info LP_TOKENS[] = {')
  for (const t of tokens) {
    push(`    { ${cString(t.path.join('.'))}, ${cString(cssName(t.path))}, ${cString(t.type ?? 'string')}, ${cString(toCssValue(t))} },`)
  }
  push('};')
  push(`#define LP_TOKEN_COUNT ${tokens.length}`)
  push()
  push('#endif')
  push()
  return lines.join('\n')
}

/** `chevronLeft` → `LP_ICON_CHEVRON_LEFT`. */
export function cIconName(name) {
  return `LP_ICON_${name.replace(/([a-z0-9])([A-Z])/g, '$1_$2').replace(/[^A-Za-z0-9]+/g, '_').toUpperCase()}`
}

/** icons.json as a C header (include/maryui/lp_icons.h): an enum in JSON order, names, and NULL-terminated path lists. */
export function toIconsC(icons, { sourceHash = 'unknown' } = {}) {
  const names = Object.keys(icons)
  const max = names.reduce((m, n) => Math.max(m, icons[n].length), 0)
  const lines = [
    `/* GENERATED by web/scripts/build-tokens.mjs from web/src/components/Icon/icons.json (sha256 ${sourceHash}) — edit the JSON, then \`npm run tokens\`. */`,
    '#ifndef MARYUI_LP_ICONS_H',
    '#define MARYUI_LP_ICONS_H',
    '',
    '#include <stddef.h>',
    '',
    '/* Icons are 24×24 stroked paths (round caps and joins) in currentColor, like Icon.tsx. */',
    '#define LP_ICON_VIEWBOX 24',
    '#define LP_ICON_STROKE 1.7f',
    `#define LP_ICON_PATH_MAX ${max}`,
    '',
    'typedef enum lp_icon {',
    ...names.map((n) => `    ${cIconName(n)},`),
    '    LP_ICON_COUNT,',
    '} lp_icon;',
    '',
    'static const char *const LP_ICON_NAMES[LP_ICON_COUNT] = {',
    ...names.map((n) => `    ${cString(n)},`),
    '};',
    '',
    `static const char *const LP_ICON_PATHS[LP_ICON_COUNT][LP_ICON_PATH_MAX + 1] = {`,
    ...names.map((n) => `    { ${icons[n].map(cString).join(', ')}, NULL },`),
    '};',
    '',
    '#endif',
    '',
  ]
  return lines.join('\n')
}

/** `appTextEdit` → `LP_OBJ_APP_TEXT_EDIT`. */
export function cObjectName(name) {
  return `LP_OBJ_${name.replace(/([a-z0-9])([A-Z])/g, '$1_$2').replace(/[^A-Za-z0-9]+/g, '_').toUpperCase()}`
}

const OBJ_FACETS = ['top', 'flat', 'front', 'under']
const OBJ_BEVELS = ['none', 'raised', 'well']
const OBJ_ROLES = ['body', 'crease', 'mark']

/**
 * objects.json as a C header (include/maryui/lp_objects.h): the geometry and
 * the per-part attributes, with an enum in JSON order.
 *
 * The prefix is `LP_OBJ_`, not `LP_OBJECT_`: tokens.json's whole `object` group
 * already owns the latter through cName(), and lp_object_icon.c includes both
 * headers, so a collision would be a macro redefinition rather than a mere
 * name clash — the same trap that kept the tokens out of an `icon` group.
 *
 * Like objects.json, this carries no colour at all. `material` names a ramp in
 * lp_tokens.h and `tint` stays a dotted token path, so the whole set still
 * regrades from the tokens alone.
 */
export function toObjectsC(objects, { sourceHash = 'unknown', materials = null } = {}) {
  const names = Object.keys(objects).filter((k) => !k.startsWith('$'))
  /* Every material tokens.json defines, not merely the ones objects.json uses:
   * `slate` is spent by the folder appearance rather than named by a part. */
  if (!materials) materials = [...new Set(names.map((n) => objects[n].material).concat(names.flatMap((n) => objects[n].parts.map((p) => p.material).filter(Boolean))))].sort()
  const max = names.reduce((m, n) => Math.max(m, objects[n].parts.length), 0)
  const cEnum = (prefix, list, value) => `${prefix}_${String(value ?? list[0]).toUpperCase()}`
  const part = (p) =>
    `{ ${cString(p.id)}, ${cString(p.d)}, ${cEnum('LP_OBJ_FACET', OBJ_FACETS, p.facet ?? 'flat')}, ${cFloat(p.tone ?? 0)}, ` +
    `${cEnum('LP_OBJ_BEVEL', OBJ_BEVELS, p.bevel ?? 'none')}, ${cEnum('LP_OBJ_ROLE', OBJ_ROLES, p.role ?? 'body')}, ` +
    `${p.material ? 1 : 0}, ${cEnum('LP_OBJ_MATERIAL', materials, p.material ?? materials[0])}, ` +
    `${p.tint ? cString(p.tint) : 'NULL'}, ${cFloat(p.min ?? 0)}, ${p.fillRule === 'evenodd' ? 1 : 0} }`
  const lines = [
    `/* GENERATED by web/scripts/build-tokens.mjs from web/src/components/ObjectIcon/objects.json (sha256 ${sourceHash}) — edit the JSON, then \`npm run tokens\`. */`,
    '#ifndef MARYUI_LP_OBJECTS_H',
    '#define MARYUI_LP_OBJECTS_H',
    '',
    '#include <stddef.h>',
    '',
    '/* Objects are lit shapes on a 32 grid, as in ObjectIcon.tsx. The geometry',
    ' * carries no colour: `material` names a ramp under LP_OBJECT_MATERIAL_* in',
    ' * lp_tokens.h, and `tint` is a dotted token path the renderer resolves. */',
    `#define LP_OBJ_GRID ${objects.$grid}`,
    `#define LP_OBJ_PART_MAX ${max}`,
    '',
    'typedef enum lp_obj_material {',
    ...materials.map((m) => `    ${cEnum('LP_OBJ_MATERIAL', materials, m)},`),
    '    LP_OBJ_MATERIAL_COUNT,',
    '} lp_obj_material;',
    '',
    `typedef enum lp_obj_facet { ${OBJ_FACETS.map((f) => cEnum('LP_OBJ_FACET', OBJ_FACETS, f)).join(', ')} } lp_obj_facet;`,
    `typedef enum lp_obj_bevel { ${OBJ_BEVELS.map((b) => cEnum('LP_OBJ_BEVEL', OBJ_BEVELS, b)).join(', ')} } lp_obj_bevel;`,
    `typedef enum lp_obj_role { ${OBJ_ROLES.map((r) => cEnum('LP_OBJ_ROLE', OBJ_ROLES, r)).join(', ')} } lp_obj_role;`,
    'typedef enum lp_obj_finish { LP_OBJ_FINISH_LIT, LP_OBJ_FINISH_GLOSSY } lp_obj_finish;',
    '',
    'typedef struct lp_obj_part {',
    '    const char *id;         /* lp_obj_def.silhouette names one of these */',
    '    const char *d;',
    '    lp_obj_facet facet;',
    '    float tone;             /* a lighting offset, capped at object.tone-step */',
    '    lp_obj_bevel bevel;',
    '    lp_obj_role role;',
    '    int has_material;       /* 0: the object\'s own material */',
    '    lp_obj_material material;',
    '    const char *tint;       /* a dotted token path: a flat fill instead of the ramp, else NULL */',
    '    float min;              /* dropped below this rendered size, in px */',
    '    int even_odd;',
    '} lp_obj_part;',
    '',
    'typedef struct lp_obj_def {',
    '    lp_obj_material material;',
    '    lp_obj_finish finish;',
    '    const char *silhouette;',
    '    const char *glyph;      /* the icons.json name drawn below the glyph tier */',
    '    const lp_obj_part *parts;',
    '    int part_count;',
    '} lp_obj_def;',
    '',
    'typedef enum lp_object {',
    ...names.map((n) => `    ${cObjectName(n)},`),
    '    LP_OBJ_COUNT,',
    '} lp_object;',
    '',
    'static const char *const LP_OBJ_NAMES[LP_OBJ_COUNT] = {',
    ...names.map((n) => `    ${cString(n)},`),
    '};',
    '',
    ...names.flatMap((n) => [
      `static const lp_obj_part ${cObjectName(n)}_PARTS[] = {`,
      ...objects[n].parts.map((p) => `    ${part(p)},`),
      '};',
    ]),
    '',
    'static const lp_obj_def LP_OBJECTS[LP_OBJ_COUNT] = {',
    ...names.map((n) => {
      const o = objects[n]
      return `    { ${cEnum('LP_OBJ_MATERIAL', materials, o.material)}, ${o.finish === 'glossy' ? 'LP_OBJ_FINISH_GLOSSY' : 'LP_OBJ_FINISH_LIT'}, ` +
        `${cString(o.silhouette)}, ${cString(o.glyph ?? n)}, ${cObjectName(n)}_PARTS, ${o.parts.length} },`
    }),
    '};',
    '',
    '#endif',
    '',
  ]
  return lines.join('\n')
}

// MARK: - Pipeline

/**
 * Everything in one call: tree in, `{ css, ts, palette, index, tokens, c, iconsC }` out.
 * `icons` is the parsed icons.json (optional); `options.sourceHash` / `options.iconsHash`
 * are stamped into the generated headers.
 */
export function buildAll(tree, icons = null, options = {}, objects = null) {
  const tokens = resolveAliases(flatten(tree))
  const sketch = toSketchPalette(tokens)
  return {
    tokens,
    css: toCss(tokens),
    ts: toTs(tokens),
    palette: sketch.palette,
    index: sketch.index,
    c: toC(tokens, { sourceHash: options.sourceHash, tree }),
    iconsC: icons ? toIconsC(icons, { sourceHash: options.iconsHash }) : null,
    objectsC: objects
      ? toObjectsC(objects, {
          sourceHash: options.objectsHash,
          materials: Object.keys(tree.object?.material ?? {}).filter((k) => !k.startsWith('$')),
        })
      : null,
  }
}
