/* GENERATED by web/scripts/build-tokens.mjs from web/src/components/Icon/icons.json (sha256 28a11998fbf9fa14) — edit the JSON, then `npm run tokens`. */
#ifndef MARYUI_LP_ICONS_H
#define MARYUI_LP_ICONS_H

#include <stddef.h>

/* Icons are 24×24 stroked paths (round caps and joins) in currentColor, like Icon.tsx. */
#define LP_ICON_VIEWBOX 24
#define LP_ICON_STROKE 1.7f
#define LP_ICON_PATH_MAX 4

typedef enum lp_icon {
    LP_ICON_FOLDER,
    LP_ICON_DOCUMENT,
    LP_ICON_IMAGE,
    LP_ICON_MUSIC,
    LP_ICON_CODE,
    LP_ICON_CHEVRON_LEFT,
    LP_ICON_CHEVRON_RIGHT,
    LP_ICON_CHEVRON_DOWN,
    LP_ICON_SEARCH,
    LP_ICON_GRID,
    LP_ICON_LIST,
    LP_ICON_GEAR,
    LP_ICON_HOME,
    LP_ICON_DESKTOP,
    LP_ICON_DOWNLOAD,
    LP_ICON_STAR,
    LP_ICON_CLOUD,
    LP_ICON_DRIVE,
    LP_ICON_CHECK,
    LP_ICON_CLOSE,
    LP_ICON_PLUS,
    LP_ICON_MINUS,
    LP_ICON_INFO,
    LP_ICON_DROP,
    LP_ICON_TERMINAL,
    LP_ICON_PENCIL,
    LP_ICON_TRASH,
    LP_ICON_COUNT,
} lp_icon;

static const char *const LP_ICON_NAMES[LP_ICON_COUNT] = {
    "folder",
    "document",
    "image",
    "music",
    "code",
    "chevronLeft",
    "chevronRight",
    "chevronDown",
    "search",
    "grid",
    "list",
    "gear",
    "home",
    "desktop",
    "download",
    "star",
    "cloud",
    "drive",
    "check",
    "close",
    "plus",
    "minus",
    "info",
    "drop",
    "terminal",
    "pencil",
    "trash",
};

static const char *const LP_ICON_PATHS[LP_ICON_COUNT][LP_ICON_PATH_MAX + 1] = {
    { "M3 7a2 2 0 0 1 2-2h4l2 2h8a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z", NULL },
    { "M7 3h7l5 5v13H7z", "M14 3v5h5", NULL },
    { "M4 5h16v14H4z", "M4 16l5-5 4 4 3-3 4 4", "M15.5 9.5a1 1 0 1 0 0-.01", NULL },
    { "M9 18V5l10-2v13", "M6 21a3 3 0 1 0 0-6 3 3 0 0 0 0 6z", "M16 19a3 3 0 1 0 0-6 3 3 0 0 0 0 6z", NULL },
    { "M8 7l-5 5 5 5", "M16 7l5 5-5 5", "M14 4l-4 16", NULL },
    { "M15 5l-7 7 7 7", NULL },
    { "M9 5l7 7-7 7", NULL },
    { "M5 9l7 7 7-7", NULL },
    { "M11 4a7 7 0 1 0 0 14 7 7 0 0 0 0-14z", "M16 16l5 5", NULL },
    { "M4 4h6v6H4z", "M14 4h6v6h-6z", "M4 14h6v6H4z", "M14 14h6v6h-6z", NULL },
    { "M4 6h16", "M4 12h16", "M4 18h16", NULL },
    { "M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8z", "M12 2v3M12 19v3M2 12h3M19 12h3M4.9 4.9l2.2 2.2M16.9 16.9l2.2 2.2M4.9 19.1l2.2-2.2M16.9 7.1l2.2-2.2", NULL },
    { "M3 11l9-7 9 7", "M5 10v10h14V10", NULL },
    { "M3 5h18v11H3z", "M8 21h8M12 16v5", NULL },
    { "M12 4v12", "M7 11l5 5 5-5", "M4 20h16", NULL },
    { "M12 3l2.8 5.9 6.2.8-4.5 4.4 1.1 6.3L12 17.4l-5.6 3 1.1-6.3L3 9.7l6.2-.8z", NULL },
    { "M7 18a4 4 0 0 1-.5-8 6 6 0 0 1 11.5 1.5A3.5 3.5 0 0 1 17.5 18z", NULL },
    { "M4 6h16v12H4z", "M4 14h16", "M16 16.5h1", NULL },
    { "M5 12l5 5 9-10", NULL },
    { "M6 6l12 12", "M18 6L6 18", NULL },
    { "M12 5v14", "M5 12h14", NULL },
    { "M5 12h14", NULL },
    { "M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18z", "M12 11v6", "M12 8h.01", NULL },
    { "M12 3s6 6.5 6 11a6 6 0 0 1-12 0c0-4.5 6-11 6-11z", NULL },
    { "M4 5h16v14H4z", "M8 9l3 3-3 3", "M13 15h4", NULL },
    { "M4 20l4-1 11-11-3-3L5 16z", "M13 6l3 3", NULL },
    { "M4 7h16", "M6 7l1 13h10l1-13", "M9 7V4h6v3", "M10 11v5M14 11v5", NULL },
};

#endif
