/* GENERATED by web/scripts/build-tokens.mjs from web/tokens/tokens.json (sha256 5515355812390460) — edit the JSON, then `npm run tokens`. */
#ifndef MARYUI_LP_TOKENS_H
#define MARYUI_LP_TOKENS_H

#include <stddef.h>
#include "maryui/lp_types.h"

#define LP_TOKENS_SOURCE_SHA "5515355812390460"

/* platinum: The raw metal ramp: near-white to deep steel, with a cool blue-violet cast. */
#define LP_PLATINUM_0 ((lp_color){ 0.9686f, 0.9686f, 0.9765f, 1.0f })  /* #f7f7f9 */
#define LP_PLATINUM_1 ((lp_color){ 0.9333f, 0.9373f, 0.949f, 1.0f })  /* #eeeff2 */
#define LP_PLATINUM_2 ((lp_color){ 0.8902f, 0.898f, 0.9137f, 1.0f })  /* #e3e5e9 */
#define LP_PLATINUM_3 ((lp_color){ 0.8314f, 0.8431f, 0.8667f, 1.0f })  /* #d4d7dd */
#define LP_PLATINUM_4 ((lp_color){ 0.7569f, 0.7725f, 0.8039f, 1.0f })  /* #c1c5cd */
#define LP_PLATINUM_5 ((lp_color){ 0.6627f, 0.6824f, 0.7216f, 1.0f })  /* #a9aeb8 */
#define LP_PLATINUM_6 ((lp_color){ 0.5451f, 0.5647f, 0.6078f, 1.0f })  /* #8b909b */
#define LP_PLATINUM_7 ((lp_color){ 0.4196f, 0.4392f, 0.4824f, 1.0f })  /* #6b707b */
#define LP_PLATINUM_8 ((lp_color){ 0.2902f, 0.3059f, 0.3412f, 1.0f })  /* #4a4e57 */
#define LP_PLATINUM_9 ((lp_color){ 0.1647f, 0.1765f, 0.2f, 1.0f })  /* #2a2d33 */

/* surface: Semantic surface colors. Every brushed surface is a vertical gradient from -top to -bottom. */
#define LP_SURFACE_WINDOW_TOP ((lp_color){ 0.9333f, 0.9373f, 0.949f, 1.0f })  /* #eeeff2 */
#define LP_SURFACE_WINDOW_BOTTOM ((lp_color){ 0.8314f, 0.8431f, 0.8667f, 1.0f })  /* #d4d7dd */
#define LP_SURFACE_TITLEBAR_TOP ((lp_color){ 0.9686f, 0.9686f, 0.9765f, 1.0f })  /* #f7f7f9 */
#define LP_SURFACE_TITLEBAR_BOTTOM ((lp_color){ 0.7569f, 0.7725f, 0.8039f, 1.0f })  /* #c1c5cd */
#define LP_SURFACE_TITLEBAR_INACTIVE_TOP ((lp_color){ 0.9333f, 0.9373f, 0.949f, 1.0f })  /* #eeeff2 */
#define LP_SURFACE_TITLEBAR_INACTIVE_BOTTOM ((lp_color){ 0.8902f, 0.898f, 0.9137f, 1.0f })  /* #e3e5e9 */
#define LP_SURFACE_MENUBAR_TOP ((lp_color){ 0.9686f, 0.9686f, 0.9765f, 1.0f })  /* #f7f7f9 */
#define LP_SURFACE_MENUBAR_BOTTOM ((lp_color){ 0.8314f, 0.8431f, 0.8667f, 1.0f })  /* #d4d7dd */
#define LP_SURFACE_RAISED_TOP ((lp_color){ 0.9686f, 0.9686f, 0.9765f, 1.0f })  /* #f7f7f9 */
#define LP_SURFACE_RAISED_BOTTOM ((lp_color){ 0.8314f, 0.8431f, 0.8667f, 1.0f })  /* #d4d7dd */
#define LP_SURFACE_PRESSED_TOP ((lp_color){ 0.7569f, 0.7725f, 0.8039f, 1.0f })  /* #c1c5cd */
#define LP_SURFACE_PRESSED_BOTTOM ((lp_color){ 0.8314f, 0.8431f, 0.8667f, 1.0f })  /* #d4d7dd */
#define LP_SURFACE_WELL ((lp_color){ 0.9686f, 0.9686f, 0.9765f, 1.0f })  /* #f7f7f9 */
#define LP_SURFACE_BODY ((lp_color){ 0.9686f, 0.9686f, 0.9765f, 1.0f })  /* #f7f7f9 */
#define LP_SURFACE_SIDEBAR ((lp_color){ 0.8902f, 0.898f, 0.9137f, 1.0f })  /* #e3e5e9 */
#define LP_SURFACE_MENU ((lp_color){ 0.9333f, 0.9373f, 0.949f, 0.94f })  /* rgba(238, 239, 242, 0.94) */
#define LP_SURFACE_SELECTED ((lp_color){ 0.2314f, 0.4902f, 0.8471f, 0.16f })  /* rgba(59, 125, 216, 0.16) */

/* ink */
#define LP_INK_PRIMARY ((lp_color){ 0.1216f, 0.1333f, 0.1569f, 1.0f })  /* #1f2228 */
#define LP_INK_SECONDARY ((lp_color){ 0.2902f, 0.3059f, 0.3412f, 1.0f })  /* #4a4e57 */
#define LP_INK_TERTIARY ((lp_color){ 0.4784f, 0.498f, 0.5412f, 1.0f })  /* #7a7f8a */
#define LP_INK_DISABLED ((lp_color){ 0.6627f, 0.6824f, 0.7216f, 1.0f })  /* #a9aeb8 */
#define LP_INK_INVERSE ((lp_color){ 0.9686f, 0.9686f, 0.9765f, 1.0f })  /* #f7f7f9 */
#define LP_INK_ON_ACCENT ((lp_color){ 1.0f, 1.0f, 1.0f, 1.0f })  /* #ffffff */
#define LP_INK_EMBOSS ((lp_color){ 1.0f, 1.0f, 1.0f, 0.8f })  /* rgba(255, 255, 255, 0.8) */

/* accent: Two appearances, as in Aqua's Blue / Graphite preference. base.css maps the chosen one onto --lp-accent-*. */
#define LP_ACCENT_BLUE_BASE ((lp_color){ 0.2314f, 0.4902f, 0.8471f, 1.0f })  /* #3b7dd8 */
#define LP_ACCENT_BLUE_DEEP ((lp_color){ 0.1647f, 0.3725f, 0.6824f, 1.0f })  /* #2a5fae */
#define LP_ACCENT_BLUE_LIGHT ((lp_color){ 0.5608f, 0.7216f, 0.9333f, 1.0f })  /* #8fb8ee */
#define LP_ACCENT_BLUE_SOFT ((lp_color){ 0.2314f, 0.4902f, 0.8471f, 0.18f })  /* rgba(59, 125, 216, 0.18) */
#define LP_ACCENT_BLUE_FOCUS_RING ((lp_color){ 0.2314f, 0.4902f, 0.8471f, 0.5f })  /* rgba(59, 125, 216, 0.5) */
#define LP_ACCENT_GRAPHITE_BASE ((lp_color){ 0.4353f, 0.4627f, 0.5137f, 1.0f })  /* #6f7683 */
#define LP_ACCENT_GRAPHITE_DEEP ((lp_color){ 0.3098f, 0.3333f, 0.3804f, 1.0f })  /* #4f5561 */
#define LP_ACCENT_GRAPHITE_LIGHT ((lp_color){ 0.6667f, 0.6902f, 0.7333f, 1.0f })  /* #aab0bb */
#define LP_ACCENT_GRAPHITE_SOFT ((lp_color){ 0.4353f, 0.4627f, 0.5137f, 0.2f })  /* rgba(111, 118, 131, 0.2) */
#define LP_ACCENT_GRAPHITE_FOCUS_RING ((lp_color){ 0.4353f, 0.4627f, 0.5137f, 0.5f })  /* rgba(111, 118, 131, 0.5) */

/* traffic: Window indicator liquids. base = liquid body, deep = the well behind it, light = the surface tint. */
#define LP_TRAFFIC_CLOSE_BASE ((lp_color){ 0.9333f, 0.4196f, 0.3725f, 1.0f })  /* #ee6b5f */
#define LP_TRAFFIC_CLOSE_DEEP ((lp_color){ 0.6588f, 0.2275f, 0.1882f, 1.0f })  /* #a83a30 */
#define LP_TRAFFIC_CLOSE_LIGHT ((lp_color){ 1.0f, 0.7176f, 0.6824f, 1.0f })  /* #ffb7ae */
#define LP_TRAFFIC_MINIMIZE_BASE ((lp_color){ 0.949f, 0.7412f, 0.3098f, 1.0f })  /* #f2bd4f */
#define LP_TRAFFIC_MINIMIZE_DEEP ((lp_color){ 0.651f, 0.4706f, 0.102f, 1.0f })  /* #a6781a */
#define LP_TRAFFIC_MINIMIZE_LIGHT ((lp_color){ 1.0f, 0.902f, 0.6667f, 1.0f })  /* #ffe6aa */
#define LP_TRAFFIC_ZOOM_BASE ((lp_color){ 0.3882f, 0.7765f, 0.3412f, 1.0f })  /* #63c657 */
#define LP_TRAFFIC_ZOOM_DEEP ((lp_color){ 0.1725f, 0.498f, 0.1569f, 1.0f })  /* #2c7f28 */
#define LP_TRAFFIC_ZOOM_LIGHT ((lp_color){ 0.7412f, 0.949f, 0.702f, 1.0f })  /* #bdf2b3 */
#define LP_TRAFFIC_INACTIVE ((lp_color){ 0.7569f, 0.7725f, 0.8039f, 1.0f })  /* #c1c5cd */
#define LP_TRAFFIC_INACTIVE_DEEP ((lp_color){ 0.5451f, 0.5647f, 0.6078f, 1.0f })  /* #8b909b */
#define LP_TRAFFIC_RIM ((lp_color){ 0.0f, 0.0f, 0.0f, 0.32f })  /* rgba(0, 0, 0, 0.32) */
#define LP_TRAFFIC_GLOSS ((lp_color){ 1.0f, 1.0f, 1.0f, 0.85f })  /* rgba(255, 255, 255, 0.85) */

/* liquid: Bubble liquid: fill level as a fraction of the well, and the two wave layers' opacities. */
#define LP_LIQUID_FILL 0.6f
#define LP_LIQUID_OPACITY_FRONT 0.95f
#define LP_LIQUID_OPACITY_BACK 0.55f

/* sheen: The specular highlight that slides across brushed surfaces. light-x is where the room light sits, as a fraction of viewport width. */
#define LP_SHEEN_COLOR ((lp_color){ 1.0f, 1.0f, 1.0f, 1.0f })  /* #ffffff */
#define LP_SHEEN_ALPHA 0.5f
#define LP_SHEEN_ALPHA_INACTIVE 0.18f
#define LP_SHEEN_ANGLE_DEG 105.0f
#define LP_SHEEN_LIGHT_X 0.35f

/* brush: Parameters of the brushed-metal tile (see src/lib/brushSvg.ts). Strokes run diagonally at atan(rise/run); keep rise and run small integers so the tile stays seamless. */
#define LP_BRUSH_OPACITY 0.34f
#define LP_BRUSH_CONTRAST 0.66f
#define LP_BRUSH_FREQ_X 0.02f
#define LP_BRUSH_FREQ_Y 0.6f
#define LP_BRUSH_OCTAVES 2
#define LP_BRUSH_SEED 7
#define LP_BRUSH_TILE 512.0f  /* 512px */
#define LP_BRUSH_ANGLE_RISE 1
#define LP_BRUSH_ANGLE_RUN 2

/* edge */
#define LP_EDGE_LIGHT ((lp_color){ 1.0f, 1.0f, 1.0f, 0.78f })  /* rgba(255, 255, 255, 0.78) */
#define LP_EDGE_DARK ((lp_color){ 0.0f, 0.0f, 0.0f, 0.2f })  /* rgba(0, 0, 0, 0.2) */
#define LP_EDGE_HAIRLINE ((lp_color){ 0.0f, 0.0f, 0.0f, 0.32f })  /* rgba(0, 0, 0, 0.32) */
#define LP_EDGE_DIVIDER ((lp_color){ 0.0f, 0.0f, 0.0f, 0.1f })  /* rgba(0, 0, 0, 0.1) */

/* radius */
#define LP_RADIUS_XS 4.0f  /* 4px */
#define LP_RADIUS_SM 6.0f  /* 6px */
#define LP_RADIUS_MD 10.0f  /* 10px */
#define LP_RADIUS_LG 14.0f  /* 14px */
#define LP_RADIUS_WINDOW 12.0f  /* 12px */
#define LP_RADIUS_PILL 999.0f  /* 999px */

/* shadow */
static const lp_shadow_layer LP_SHADOW_WINDOW[] = {
    { 0, 0.0f, 14.0f, 36.0f, 0.0f, ((lp_color){ 0.0784f, 0.0863f, 0.1098f, 0.26f }) },
    { 0, 0.0f, 0.0f, 0.0f, 1.0f, ((lp_color){ 0.0f, 0.0f, 0.0f, 0.28f }) },
};
#define LP_SHADOW_WINDOW_COUNT 2
static const lp_shadow_layer LP_SHADOW_WINDOW_FOCUSED[] = {
    { 0, 0.0f, 24.0f, 56.0f, 0.0f, ((lp_color){ 0.0784f, 0.0863f, 0.1098f, 0.4f }) },
    { 0, 0.0f, 0.0f, 0.0f, 1.0f, ((lp_color){ 0.0f, 0.0f, 0.0f, 0.34f }) },
};
#define LP_SHADOW_WINDOW_FOCUSED_COUNT 2
static const lp_shadow_layer LP_SHADOW_MENU[] = {
    { 0, 0.0f, 10.0f, 30.0f, 0.0f, ((lp_color){ 0.0784f, 0.0863f, 0.1098f, 0.3f }) },
    { 0, 0.0f, 0.0f, 0.0f, 1.0f, ((lp_color){ 0.0f, 0.0f, 0.0f, 0.22f }) },
};
#define LP_SHADOW_MENU_COUNT 2
static const lp_shadow_layer LP_SHADOW_EMBOSS_RAISED[] = {
    { 1, 0.0f, 1.0f, 0.0f, 0.0f, ((lp_color){ 1.0f, 1.0f, 1.0f, 0.78f }) },
    { 1, 0.0f, -1.0f, 0.0f, 0.0f, ((lp_color){ 0.0f, 0.0f, 0.0f, 0.2f }) },
};
#define LP_SHADOW_EMBOSS_RAISED_COUNT 2
static const lp_shadow_layer LP_SHADOW_EMBOSS_WELL[] = {
    { 1, 0.0f, 1.0f, 3.0f, 0.0f, ((lp_color){ 0.0f, 0.0f, 0.0f, 0.28f }) },
    { 1, 0.0f, 0.0f, 0.0f, 1.0f, ((lp_color){ 0.0f, 0.0f, 0.0f, 0.12f }) },
};
#define LP_SHADOW_EMBOSS_WELL_COUNT 2
static const lp_shadow_layer LP_SHADOW_EMBOSS_PRESSED[] = {
    { 1, 0.0f, 2.0f, 4.0f, 0.0f, ((lp_color){ 0.0f, 0.0f, 0.0f, 0.3f }) },
};
#define LP_SHADOW_EMBOSS_PRESSED_COUNT 1

/* space */
#define LP_SPACE_1 4.0f  /* 4px */
#define LP_SPACE_2 8.0f  /* 8px */
#define LP_SPACE_3 12.0f  /* 12px */
#define LP_SPACE_4 16.0f  /* 16px */
#define LP_SPACE_5 20.0f  /* 20px */
#define LP_SPACE_6 24.0f  /* 24px */
#define LP_SPACE_7 32.0f  /* 32px */
#define LP_SPACE_8 40.0f  /* 40px */

/* size */
#define LP_SIZE_MENUBAR_HEIGHT 24.0f  /* 24px */
#define LP_SIZE_TITLEBAR_HEIGHT 28.0f  /* 28px */
#define LP_SIZE_TRAFFIC 12.0f  /* 12px */
#define LP_SIZE_TRAFFIC_GAP 8.0f  /* 8px */
#define LP_SIZE_CONTROL_HEIGHT 22.0f  /* 22px */
#define LP_SIZE_CONTROL_HEIGHT_SM 18.0f  /* 18px */
#define LP_SIZE_RESIZE_GRIP 6.0f  /* 6px */
#define LP_SIZE_RESIZE_CORNER 14.0f  /* 14px */
#define LP_SIZE_WINDOW_MIN_W 240.0f  /* 240px */
#define LP_SIZE_WINDOW_MIN_H 160.0f  /* 160px */
#define LP_SIZE_SPOTLIGHT_WIDTH 560.0f  /* 560px */
#define LP_SIZE_SPOTLIGHT_BAR_HEIGHT 44.0f  /* 44px */
#define LP_SIZE_SPOTLIGHT_TILE 56.0f  /* 56px */

/* font */
static const char *const LP_FONT_UI_FAMILIES[] = { "-apple-system", "BlinkMacSystemFont", "SF Pro Text", "Helvetica Neue", "Helvetica", "Arial", "Inter", "sans-serif", NULL };
#define LP_FONT_UI_PANGO "-apple-system, BlinkMacSystemFont, SF Pro Text, Helvetica Neue, Helvetica, Arial, Inter, sans-serif"
static const char *const LP_FONT_DISPLAY_FAMILIES[] = { "Iowan Old Style", "Palatino Linotype", "Palatino", "Georgia", "P052", "serif", NULL };
#define LP_FONT_DISPLAY_PANGO "Iowan Old Style, Palatino Linotype, Palatino, Georgia, P052, serif"
static const char *const LP_FONT_MONO_FAMILIES[] = { "SFMono-Regular", "ui-monospace", "Menlo", "Consolas", "JetBrains Mono", "monospace", NULL };
#define LP_FONT_MONO_PANGO "SFMono-Regular, ui-monospace, Menlo, Consolas, JetBrains Mono, monospace"

/* text */
#define LP_TEXT_XS 11.0f  /* 11px */
#define LP_TEXT_SM 12.0f  /* 12px */
#define LP_TEXT_MD 13.0f  /* 13px */
#define LP_TEXT_LG 15.0f  /* 15px */
#define LP_TEXT_XL 20.0f  /* 20px */
#define LP_TEXT_XXL 28.0f  /* 28px */
#define LP_TEXT_WEIGHT_REGULAR 400
#define LP_TEXT_WEIGHT_MEDIUM 500
#define LP_TEXT_WEIGHT_SEMIBOLD 600
#define LP_TEXT_WEIGHT_BOLD 700
#define LP_TEXT_LEADING_TIGHT 1.2f
#define LP_TEXT_LEADING_NORMAL 1.45f

/* motion: Durations for discrete transitions; springs as {frequency Hz, damping ratio}; slosh is the bubble pendulum. */
#define LP_MOTION_FAST_MS 120.0f  /* 120ms */
#define LP_MOTION_NORMAL_MS 200.0f  /* 200ms */
#define LP_MOTION_SLOW_MS 360.0f  /* 360ms */
#define LP_MOTION_EASE_OUT ((lp_cubic_bezier){ 0.2f, 0.8f, 0.2f, 1.0f })  /* cubic-bezier(0.2, 0.8, 0.2, 1) */
#define LP_MOTION_EASE_SPRING ((lp_cubic_bezier){ 0.34f, 1.56f, 0.64f, 1.0f })  /* cubic-bezier(0.34, 1.56, 0.64, 1) */
#define LP_MOTION_SPRING_SHEEN_FREQUENCY 1.2f
#define LP_MOTION_SPRING_SHEEN_DAMPING 0.45f
#define LP_MOTION_SPRING_TILT_FREQUENCY 1.6f
#define LP_MOTION_SPRING_TILT_DAMPING 0.6f
#define LP_MOTION_SPRING_JELLY_FREQUENCY 2.2f
#define LP_MOTION_SPRING_JELLY_DAMPING 0.55f
#define LP_MOTION_SPRING_FLY_FREQUENCY 2.3f
#define LP_MOTION_SPRING_FLY_DAMPING 0.8f
#define LP_MOTION_SLOSH_FREQUENCY 1.7f
#define LP_MOTION_SLOSH_DAMPING 0.14f
#define LP_MOTION_SLOSH_GAIN 0.00005f
#define LP_MOTION_SLOSH_MAX 0.5f
#define LP_MOTION_SLOSH_MAX_ACCEL 12000
#define LP_MOTION_JELLY_MAX_SCALE 0.035f
#define LP_MOTION_JELLY_MAX_SKEW 2.5f
#define LP_MOTION_TILT_MAX 3
#define LP_MOTION_VELOCITY_REF 2500
#define LP_MOTION_SWIRL_PERIOD_MS 7000.0f  /* 7s */
#define LP_MOTION_DRIFT_PERIOD_MS 45000.0f  /* 45s */

/* z */
#define LP_Z_WALLPAPER 0
#define LP_Z_WINDOWS 100
#define LP_Z_MENUBAR 600
#define LP_Z_MENUS 700
#define LP_Z_SPOTLIGHT 800

/* Springs: { frequency Hz, damping ratio }, one per group with those two leaves. */
#define LP_MOTION_SPRING_SHEEN ((lp_spring_params){ 1.2f, 0.45f })
#define LP_MOTION_SPRING_TILT ((lp_spring_params){ 1.6f, 0.6f })
#define LP_MOTION_SPRING_JELLY ((lp_spring_params){ 2.2f, 0.55f })
#define LP_MOTION_SPRING_FLY ((lp_spring_params){ 2.3f, 0.8f })

/* Every token by name, in source order, for the Gallery's Tokens tab and for tests. */
typedef struct lp_token_info { const char *name; const char *css_name; const char *type; const char *value; } lp_token_info;
static const lp_token_info LP_TOKENS[] = {
    { "platinum.0", "--lp-platinum-0", "color", "#f7f7f9" },
    { "platinum.1", "--lp-platinum-1", "color", "#eeeff2" },
    { "platinum.2", "--lp-platinum-2", "color", "#e3e5e9" },
    { "platinum.3", "--lp-platinum-3", "color", "#d4d7dd" },
    { "platinum.4", "--lp-platinum-4", "color", "#c1c5cd" },
    { "platinum.5", "--lp-platinum-5", "color", "#a9aeb8" },
    { "platinum.6", "--lp-platinum-6", "color", "#8b909b" },
    { "platinum.7", "--lp-platinum-7", "color", "#6b707b" },
    { "platinum.8", "--lp-platinum-8", "color", "#4a4e57" },
    { "platinum.9", "--lp-platinum-9", "color", "#2a2d33" },
    { "surface.window-top", "--lp-surface-window-top", "color", "#eeeff2" },
    { "surface.window-bottom", "--lp-surface-window-bottom", "color", "#d4d7dd" },
    { "surface.titlebar-top", "--lp-surface-titlebar-top", "color", "#f7f7f9" },
    { "surface.titlebar-bottom", "--lp-surface-titlebar-bottom", "color", "#c1c5cd" },
    { "surface.titlebar-inactive-top", "--lp-surface-titlebar-inactive-top", "color", "#eeeff2" },
    { "surface.titlebar-inactive-bottom", "--lp-surface-titlebar-inactive-bottom", "color", "#e3e5e9" },
    { "surface.menubar-top", "--lp-surface-menubar-top", "color", "#f7f7f9" },
    { "surface.menubar-bottom", "--lp-surface-menubar-bottom", "color", "#d4d7dd" },
    { "surface.raised-top", "--lp-surface-raised-top", "color", "#f7f7f9" },
    { "surface.raised-bottom", "--lp-surface-raised-bottom", "color", "#d4d7dd" },
    { "surface.pressed-top", "--lp-surface-pressed-top", "color", "#c1c5cd" },
    { "surface.pressed-bottom", "--lp-surface-pressed-bottom", "color", "#d4d7dd" },
    { "surface.well", "--lp-surface-well", "color", "#f7f7f9" },
    { "surface.body", "--lp-surface-body", "color", "#f7f7f9" },
    { "surface.sidebar", "--lp-surface-sidebar", "color", "#e3e5e9" },
    { "surface.menu", "--lp-surface-menu", "color", "rgba(238, 239, 242, 0.94)" },
    { "surface.selected", "--lp-surface-selected", "color", "rgba(59, 125, 216, 0.16)" },
    { "ink.primary", "--lp-ink-primary", "color", "#1f2228" },
    { "ink.secondary", "--lp-ink-secondary", "color", "#4a4e57" },
    { "ink.tertiary", "--lp-ink-tertiary", "color", "#7a7f8a" },
    { "ink.disabled", "--lp-ink-disabled", "color", "#a9aeb8" },
    { "ink.inverse", "--lp-ink-inverse", "color", "#f7f7f9" },
    { "ink.on-accent", "--lp-ink-on-accent", "color", "#ffffff" },
    { "ink.emboss", "--lp-ink-emboss", "color", "rgba(255, 255, 255, 0.8)" },
    { "accent.blue.base", "--lp-accent-blue-base", "color", "#3b7dd8" },
    { "accent.blue.deep", "--lp-accent-blue-deep", "color", "#2a5fae" },
    { "accent.blue.light", "--lp-accent-blue-light", "color", "#8fb8ee" },
    { "accent.blue.soft", "--lp-accent-blue-soft", "color", "rgba(59, 125, 216, 0.18)" },
    { "accent.blue.focus-ring", "--lp-accent-blue-focus-ring", "color", "rgba(59, 125, 216, 0.5)" },
    { "accent.graphite.base", "--lp-accent-graphite-base", "color", "#6f7683" },
    { "accent.graphite.deep", "--lp-accent-graphite-deep", "color", "#4f5561" },
    { "accent.graphite.light", "--lp-accent-graphite-light", "color", "#aab0bb" },
    { "accent.graphite.soft", "--lp-accent-graphite-soft", "color", "rgba(111, 118, 131, 0.2)" },
    { "accent.graphite.focus-ring", "--lp-accent-graphite-focus-ring", "color", "rgba(111, 118, 131, 0.5)" },
    { "traffic.close.base", "--lp-traffic-close-base", "color", "#ee6b5f" },
    { "traffic.close.deep", "--lp-traffic-close-deep", "color", "#a83a30" },
    { "traffic.close.light", "--lp-traffic-close-light", "color", "#ffb7ae" },
    { "traffic.minimize.base", "--lp-traffic-minimize-base", "color", "#f2bd4f" },
    { "traffic.minimize.deep", "--lp-traffic-minimize-deep", "color", "#a6781a" },
    { "traffic.minimize.light", "--lp-traffic-minimize-light", "color", "#ffe6aa" },
    { "traffic.zoom.base", "--lp-traffic-zoom-base", "color", "#63c657" },
    { "traffic.zoom.deep", "--lp-traffic-zoom-deep", "color", "#2c7f28" },
    { "traffic.zoom.light", "--lp-traffic-zoom-light", "color", "#bdf2b3" },
    { "traffic.inactive", "--lp-traffic-inactive", "color", "#c1c5cd" },
    { "traffic.inactive-deep", "--lp-traffic-inactive-deep", "color", "#8b909b" },
    { "traffic.rim", "--lp-traffic-rim", "color", "rgba(0, 0, 0, 0.32)" },
    { "traffic.gloss", "--lp-traffic-gloss", "color", "rgba(255, 255, 255, 0.85)" },
    { "liquid.fill", "--lp-liquid-fill", "number", "0.6" },
    { "liquid.opacity-front", "--lp-liquid-opacity-front", "number", "0.95" },
    { "liquid.opacity-back", "--lp-liquid-opacity-back", "number", "0.55" },
    { "sheen.color", "--lp-sheen-color", "color", "#ffffff" },
    { "sheen.alpha", "--lp-sheen-alpha", "number", "0.5" },
    { "sheen.alpha-inactive", "--lp-sheen-alpha-inactive", "number", "0.18" },
    { "sheen.angle", "--lp-sheen-angle", "dimension", "105deg" },
    { "sheen.light-x", "--lp-sheen-light-x", "number", "0.35" },
    { "brush.opacity", "--lp-brush-opacity", "number", "0.34" },
    { "brush.contrast", "--lp-brush-contrast", "number", "0.66" },
    { "brush.freq-x", "--lp-brush-freq-x", "number", "0.02" },
    { "brush.freq-y", "--lp-brush-freq-y", "number", "0.6" },
    { "brush.octaves", "--lp-brush-octaves", "number", "2" },
    { "brush.seed", "--lp-brush-seed", "number", "7" },
    { "brush.tile", "--lp-brush-tile", "dimension", "512px" },
    { "brush.angle.rise", "--lp-brush-angle-rise", "number", "1" },
    { "brush.angle.run", "--lp-brush-angle-run", "number", "2" },
    { "edge.light", "--lp-edge-light", "color", "rgba(255, 255, 255, 0.78)" },
    { "edge.dark", "--lp-edge-dark", "color", "rgba(0, 0, 0, 0.2)" },
    { "edge.hairline", "--lp-edge-hairline", "color", "rgba(0, 0, 0, 0.32)" },
    { "edge.divider", "--lp-edge-divider", "color", "rgba(0, 0, 0, 0.1)" },
    { "radius.xs", "--lp-radius-xs", "dimension", "4px" },
    { "radius.sm", "--lp-radius-sm", "dimension", "6px" },
    { "radius.md", "--lp-radius-md", "dimension", "10px" },
    { "radius.lg", "--lp-radius-lg", "dimension", "14px" },
    { "radius.window", "--lp-radius-window", "dimension", "12px" },
    { "radius.pill", "--lp-radius-pill", "dimension", "999px" },
    { "shadow.window", "--lp-shadow-window", "shadow", "0 14px 36px 0 rgba(20, 22, 28, 0.26), 0 0 0 1px rgba(0, 0, 0, 0.28)" },
    { "shadow.window-focused", "--lp-shadow-window-focused", "shadow", "0 24px 56px 0 rgba(20, 22, 28, 0.4), 0 0 0 1px rgba(0, 0, 0, 0.34)" },
    { "shadow.menu", "--lp-shadow-menu", "shadow", "0 10px 30px 0 rgba(20, 22, 28, 0.3), 0 0 0 1px rgba(0, 0, 0, 0.22)" },
    { "shadow.emboss-raised", "--lp-shadow-emboss-raised", "shadow", "inset 0 1px 0 0 rgba(255, 255, 255, 0.78), inset 0 -1px 0 0 rgba(0, 0, 0, 0.2)" },
    { "shadow.emboss-well", "--lp-shadow-emboss-well", "shadow", "inset 0 1px 3px 0 rgba(0, 0, 0, 0.28), inset 0 0 0 1px rgba(0, 0, 0, 0.12)" },
    { "shadow.emboss-pressed", "--lp-shadow-emboss-pressed", "shadow", "inset 0 2px 4px 0 rgba(0, 0, 0, 0.3)" },
    { "space.1", "--lp-space-1", "dimension", "4px" },
    { "space.2", "--lp-space-2", "dimension", "8px" },
    { "space.3", "--lp-space-3", "dimension", "12px" },
    { "space.4", "--lp-space-4", "dimension", "16px" },
    { "space.5", "--lp-space-5", "dimension", "20px" },
    { "space.6", "--lp-space-6", "dimension", "24px" },
    { "space.7", "--lp-space-7", "dimension", "32px" },
    { "space.8", "--lp-space-8", "dimension", "40px" },
    { "size.menubar-height", "--lp-size-menubar-height", "dimension", "24px" },
    { "size.titlebar-height", "--lp-size-titlebar-height", "dimension", "28px" },
    { "size.traffic", "--lp-size-traffic", "dimension", "12px" },
    { "size.traffic-gap", "--lp-size-traffic-gap", "dimension", "8px" },
    { "size.control-height", "--lp-size-control-height", "dimension", "22px" },
    { "size.control-height-sm", "--lp-size-control-height-sm", "dimension", "18px" },
    { "size.resize-grip", "--lp-size-resize-grip", "dimension", "6px" },
    { "size.resize-corner", "--lp-size-resize-corner", "dimension", "14px" },
    { "size.window-min-w", "--lp-size-window-min-w", "dimension", "240px" },
    { "size.window-min-h", "--lp-size-window-min-h", "dimension", "160px" },
    { "size.spotlight-width", "--lp-size-spotlight-width", "dimension", "560px" },
    { "size.spotlight-bar-height", "--lp-size-spotlight-bar-height", "dimension", "44px" },
    { "size.spotlight-tile", "--lp-size-spotlight-tile", "dimension", "56px" },
    { "font.ui", "--lp-font-ui", "fontFamily", "-apple-system, BlinkMacSystemFont, \"SF Pro Text\", \"Helvetica Neue\", Helvetica, Arial, Inter, sans-serif" },
    { "font.display", "--lp-font-display", "fontFamily", "\"Iowan Old Style\", \"Palatino Linotype\", Palatino, Georgia, P052, serif" },
    { "font.mono", "--lp-font-mono", "fontFamily", "SFMono-Regular, ui-monospace, Menlo, Consolas, \"JetBrains Mono\", monospace" },
    { "text.xs", "--lp-text-xs", "dimension", "11px" },
    { "text.sm", "--lp-text-sm", "dimension", "12px" },
    { "text.md", "--lp-text-md", "dimension", "13px" },
    { "text.lg", "--lp-text-lg", "dimension", "15px" },
    { "text.xl", "--lp-text-xl", "dimension", "20px" },
    { "text.xxl", "--lp-text-xxl", "dimension", "28px" },
    { "text.weight-regular", "--lp-text-weight-regular", "fontWeight", "400" },
    { "text.weight-medium", "--lp-text-weight-medium", "fontWeight", "500" },
    { "text.weight-semibold", "--lp-text-weight-semibold", "fontWeight", "600" },
    { "text.weight-bold", "--lp-text-weight-bold", "fontWeight", "700" },
    { "text.leading-tight", "--lp-text-leading-tight", "number", "1.2" },
    { "text.leading-normal", "--lp-text-leading-normal", "number", "1.45" },
    { "motion.fast", "--lp-motion-fast", "duration", "120ms" },
    { "motion.normal", "--lp-motion-normal", "duration", "200ms" },
    { "motion.slow", "--lp-motion-slow", "duration", "360ms" },
    { "motion.ease-out", "--lp-motion-ease-out", "cubicBezier", "cubic-bezier(0.2, 0.8, 0.2, 1)" },
    { "motion.ease-spring", "--lp-motion-ease-spring", "cubicBezier", "cubic-bezier(0.34, 1.56, 0.64, 1)" },
    { "motion.spring-sheen.frequency", "--lp-motion-spring-sheen-frequency", "number", "1.2" },
    { "motion.spring-sheen.damping", "--lp-motion-spring-sheen-damping", "number", "0.45" },
    { "motion.spring-tilt.frequency", "--lp-motion-spring-tilt-frequency", "number", "1.6" },
    { "motion.spring-tilt.damping", "--lp-motion-spring-tilt-damping", "number", "0.6" },
    { "motion.spring-jelly.frequency", "--lp-motion-spring-jelly-frequency", "number", "2.2" },
    { "motion.spring-jelly.damping", "--lp-motion-spring-jelly-damping", "number", "0.55" },
    { "motion.spring-fly.frequency", "--lp-motion-spring-fly-frequency", "number", "2.3" },
    { "motion.spring-fly.damping", "--lp-motion-spring-fly-damping", "number", "0.8" },
    { "motion.slosh-frequency", "--lp-motion-slosh-frequency", "number", "1.7" },
    { "motion.slosh-damping", "--lp-motion-slosh-damping", "number", "0.14" },
    { "motion.slosh-gain", "--lp-motion-slosh-gain", "number", "0.00005" },
    { "motion.slosh-max", "--lp-motion-slosh-max", "number", "0.5" },
    { "motion.slosh-max-accel", "--lp-motion-slosh-max-accel", "number", "12000" },
    { "motion.jelly-max-scale", "--lp-motion-jelly-max-scale", "number", "0.035" },
    { "motion.jelly-max-skew", "--lp-motion-jelly-max-skew", "number", "2.5" },
    { "motion.tilt-max", "--lp-motion-tilt-max", "number", "3" },
    { "motion.velocity-ref", "--lp-motion-velocity-ref", "number", "2500" },
    { "motion.swirl-period", "--lp-motion-swirl-period", "duration", "7s" },
    { "motion.drift-period", "--lp-motion-drift-period", "duration", "45s" },
    { "z.wallpaper", "--lp-z-wallpaper", "number", "0" },
    { "z.windows", "--lp-z-windows", "number", "100" },
    { "z.menubar", "--lp-z-menubar", "number", "600" },
    { "z.menus", "--lp-z-menus", "number", "700" },
    { "z.spotlight", "--lp-z-spotlight", "number", "800" },
};
#define LP_TOKEN_COUNT 155

#endif
